@{
	'HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features'=@{
        'WiFiSenseCredShared'=@{
            Val=0
            Type='dword'
        }
		'WiFiSenseOpen'=@{
            Val=0
            Type='dword'
        }
    }
}