@{
    'HKCU:\SOFTWARE\Classes\AppX4hxtad77fbk3jkkeerkrm0ze94wjf3s9'=@{
        'NoOpenWith'=@{
            Val=''
            Type='String'
        }
        'NoStaticDefaultVerb'=@{
            Val=''
            Type='String'
        }
    }
    'HKCU:\SOFTWARE\Classes\AppXd4nrz8ff68srnhf9t5a8sbjyar1cr723'=@{
        'NoOpenWith'=@{
            Val=''
            Type='String'
        }
        'NoStaticDefaultVerb'=@{
            Val=''
            Type='String'
        }
    }
}