@{
    'HKCU:\Control Panel\Accessibility\StickyKeys'=@{
        'Flags'=@{
            Val=506
            Type='int'
        }
    }
	'HKCU:\Control Panel\Accessibility\Keyboard Response'=@{
        'Flags'=@{
            Val=122
            Type='int'
        }
    }
	'HKCU:\Control Panel\Accessibility\ToggleKeys'=@{
        'Flags'=@{
            Val=58
            Type='int'
        }
    }
	'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'=@{
        'Hidden'=@{
            Val=1
            Type='int'
        }
        'HideFileExt'=@{
            Val=0
            Type='int'
        }
		'HideDrivesWithNoMedia'=@{
            Val=0
            Type='int'
        }
		'LaunchTo'=@{
            Val=1
            Type='int'
        }
    }
	'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize'=@{
        'AppsUseLightTheme'=@{
            Val=0
            Type='int'
        }
    }
}